/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.43
 * Generated at: 2025-11-14 14:10:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.hms.entity.Specialist;
import java.util.List;
import com.hms.db.DBConnection;
import com.hms.dao.SpecialistDAO;

public final class doctor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/component/allcss.jsp", Long.valueOf(1763046081998L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1754389174666L));
    _jspx_dependants.put("/admin/navbar.jsp", Long.valueOf(1763123131461L));
    _jspx_dependants.put("jar:file:/Z:/project_workspace_new/Doctor-Patient-Portal-AdvanceJavaWebProject-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Doctor-Patient-Portal/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hms.db.DBConnection");
    _jspx_imports_classes.add("com.hms.dao.SpecialistDAO");
    _jspx_imports_classes.add("com.hms.entity.Specialist");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Add Doctor</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("    href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("    crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome CSS (for icons) -->\r\n");
      out.write("<link\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\"\r\n");
      out.write("    integrity=\"sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==\"\r\n");
      out.write("    crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script\r\n");
      out.write("    src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Global Custom Styles -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       THEME COLORS & VARIABLES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    :root {\r\n");
      out.write("        --primary-color: #4568dc;\r\n");
      out.write("        --primary-hover: #3654b3;\r\n");
      out.write("        --accent-color: #00c6ff;\r\n");
      out.write("        --light-bg: #f8f9fa;\r\n");
      out.write("        --dark-text: #2d2d2d;\r\n");
      out.write("        --card-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        --transition-speed: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif;\r\n");
      out.write("        background-color: var(--light-bg);\r\n");
      out.write("        color: var(--dark-text);\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        REUSABLE CLASSES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-bg-color { background-color: var(--primary-color) !important; }\r\n");
      out.write("    .myP-color { color: var(--primary-color) !important; }\r\n");
      out.write("    .my-hover:hover { color: var(--primary-hover) !important; }\r\n");
      out.write("\r\n");
      out.write("    /* Button Enhancements */\r\n");
      out.write("    .btn.my-bg-color {\r\n");
      out.write("        background-color: var(--primary-color);\r\n");
      out.write("        border-color: var(--primary-color);\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: background-color var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("    .btn.my-bg-color:hover {\r\n");
      out.write("        background-color: var(--primary-hover);\r\n");
      out.write("        border-color: var(--primary-hover);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       NAVBAR STYLING\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .navbar {\r\n");
      out.write("        box-shadow: 0 2px 6px rgba(0,0,0,0.1);\r\n");
      out.write("        background: linear-gradient(90deg, var(--primary-color), var(--accent-color));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .navbar-brand {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #fff !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .nav-link, .navbar .dropdown-toggle {\r\n");
      out.write("        color: #fff !important;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: color var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .nav-link:hover {\r\n");
      out.write("        color: #e2e2e2 !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-menu {\r\n");
      out.write("        border: none;\r\n");
      out.write("        box-shadow: var(--card-shadow);\r\n");
      out.write("        border-radius: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        FORMS & INPUTS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .form-control, .form-select {\r\n");
      out.write("        border-radius: 0.5rem;\r\n");
      out.write("        transition: all var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control:focus, .form-select:focus {\r\n");
      out.write("        border-color: var(--primary-color);\r\n");
      out.write("        box-shadow: 0 0 0 0.25rem rgba(69,104,220,0.25);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        CARDS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-card {\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 0.75rem;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        box-shadow: var(--card-shadow);\r\n");
      out.write("        transition: transform 0.2s ease, box-shadow 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .my-card:hover {\r\n");
      out.write("        transform: translateY(-3px);\r\n");
      out.write("        box-shadow: 0 8px 18px rgba(0, 0, 0, 0.12);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        TABLE STYLING\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .table thead {\r\n");
      out.write("        background-color: var(--primary-color);\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table th {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        BACKGROUND UTILITIES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-bg-img {\r\n");
      out.write("        background: linear-gradient(rgba(0, 0, 0, .4), rgba(0, 0, 0, .4)),\r\n");
      out.write("                    url(\"img/hospital1.jpg\") center/cover no-repeat;\r\n");
      out.write("        height: 25vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-shadow: 0 2px 4px rgba(0,0,0,0.6);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       LOGIN & SIGNUP PAGES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .login-container {\r\n");
      out.write("        min-height: 90vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        padding: 2rem 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-card {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 450px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       RESPONSIVENESS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .navbar .nav-link { font-size: 0.95rem; }\r\n");
      out.write("        .my-bg-img { height: 20vh; background-position: top center; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("        .login-card { padding: 1rem; }\r\n");
      out.write("        .my-bg-img { height: 18vh; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        ANIMATION HELPERS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .fade-in {\r\n");
      out.write("        animation: fadeIn 0.8s ease-in-out forwards;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeIn {\r\n");
      out.write("        from { opacity: 0; transform: translateY(10px); }\r\n");
      out.write("        to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* === PAGE BASE AND BACKGROUND === */\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8faff; /* Very light, clean base */\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding-top: 70px; /* CRUCIAL: Space for fixed navbar */\r\n");
      out.write("	display: flex; /* Flexbox for centering */\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Ensure the included navbar is fixed */\r\n");
      out.write(".navbar {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	z-index: 1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Blurred Background Image (Matches previous style) */\r\n");
      out.write("body::before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	/* Assuming the path for the background image is correct */\r\n");
      out.write("	background: url('../img/hospital1.jpg') center center/cover no-repeat\r\n");
      out.write("		fixed;\r\n");
      out.write("	filter: blur(8px) brightness(1.05);\r\n");
      out.write("	/* Strong blur and slightly brighter */\r\n");
      out.write("	opacity: 0.9; /* Allows the white cards to pop */\r\n");
      out.write("	z-index: -1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Main Content Wrapper (Container for form) */\r\n");
      out.write(".form-wrapper {\r\n");
      out.write("	flex-grow: 1; /* Allows it to take up available space */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center; /* Center vertically */\r\n");
      out.write("	justify-content: center; /* Center horizontally */\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Killer UI Card Style (Glass Morphism) */\r\n");
      out.write(".my-card {\r\n");
      out.write("	/* Glass effect background */\r\n");
      out.write("	background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("	backdrop-filter: blur(15px);\r\n");
      out.write("	-webkit-backdrop-filter: blur(15px);\r\n");
      out.write("	border-radius: 1.5rem;\r\n");
      out.write("	border: 1px solid rgba(220, 220, 220, 0.7);\r\n");
      out.write("	box-shadow: 0 15px 50px rgba(0, 0, 0, 0.15);\r\n");
      out.write("	transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);\r\n");
      out.write("	width: 100%; /* Ensure it takes full column width */\r\n");
      out.write("	max-width: 650px; /* Limit max width for readability */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".my-card:hover {\r\n");
      out.write("	transform: translateY(-5px);\r\n");
      out.write("	box-shadow: 0 25px 60px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".my-card h3 {\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("	color: #1e88e5; /* Primary Blue */\r\n");
      out.write("	font-size: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Form Element Styling */\r\n");
      out.write(".form-control, .form-select {\r\n");
      out.write("	border-radius: 0.75rem;\r\n");
      out.write("	border: 1px solid #e0e0e0;\r\n");
      out.write("	padding: 0.8rem 1rem;\r\n");
      out.write("	transition: border-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus, .form-select:focus {\r\n");
      out.write("	border-color: #1e88e5;\r\n");
      out.write("	box-shadow: 0 0 0 0.25rem rgba(30, 136, 229, 0.25);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-label {\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	margin-bottom: 0.3rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button Styling */\r\n");
      out.write(".btn-primary {\r\n");
      out.write("	background-color: #1e88e5;\r\n");
      out.write("	border-color: #1e88e5;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	border-radius: 0.75rem;\r\n");
      out.write("	letter-spacing: 0.5px;\r\n");
      out.write("	padding: 0.75rem 1rem;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.2s ease, box-shadow\r\n");
      out.write("		0.3s ease;\r\n");
      out.write("	box-shadow: 0 4px 12px rgba(30, 136, 229, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("	background-color: #1565c0;\r\n");
      out.write("	border-color: #1565c0;\r\n");
      out.write("	transform: translateY(-1px);\r\n");
      out.write("	box-shadow: 0 6px 15px rgba(30, 136, 229, 0.6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive adjustments for the row/card centering */\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	.my-card {\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("		margin-bottom: 20px;\r\n");
      out.write("		padding: 1.5rem !important;\r\n");
      out.write("	}\r\n");
      out.write("	.my-card h3 {\r\n");
      out.write("		font-size: 1.75rem;\r\n");
      out.write("	}\r\n");
      out.write("	/* Ensure all fields stack on mobile */\r\n");
      out.write("	.row.g-3>div[class*=\"col-md-6\"] {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function validateEmail() {\r\n");
      out.write("		const emailInput = document.getElementById(\"email\");\r\n");
      out.write("		const emailError = document.getElementById(\"emailError\");\r\n");
      out.write("		const emailPattern = /^(?!.*\\.\\.)[a-zA-Z0-9._%+-]{2,64}@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/;\r\n");
      out.write("\r\n");
      out.write("		const emailValue = emailInput.value.trim();\r\n");
      out.write("		emailError.textContent = \"\"; // clear previous error\r\n");
      out.write("		emailInput.classList.remove(\"is-invalid\", \"is-valid\"); // reset styles\r\n");
      out.write("\r\n");
      out.write("		// Check if empty\r\n");
      out.write("		if (emailValue === \"\") {\r\n");
      out.write("			emailError.textContent = \"Email address is required.\";\r\n");
      out.write("			emailInput.classList.add(\"is-invalid\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Check pattern validity\r\n");
      out.write("		if (!emailPattern.test(emailValue)) {\r\n");
      out.write("			emailError.textContent = \"Please enter a valid email address (e.g., user@example.com)\";\r\n");
      out.write("			emailInput.classList.add(\"is-invalid\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Valid email — green border\r\n");
      out.write("		emailInput.classList.add(\"is-valid\");\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function validateDOB() {\r\n");
      out.write("		const dobInput = document.getElementById(\"dateOfBirth\");\r\n");
      out.write("		const dobError = document.getElementById(\"dobError\");\r\n");
      out.write("		const dobValue = dobInput.value;\r\n");
      out.write("\r\n");
      out.write("		dobError.textContent = \"\";\r\n");
      out.write("		dobInput.classList.remove(\"is-invalid\", \"is-valid\");\r\n");
      out.write("\r\n");
      out.write("		if (!dobValue) {\r\n");
      out.write("			dobError.textContent = \"Date of Birth is required.\";\r\n");
      out.write("			dobInput.classList.add(\"is-invalid\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		const dob = new Date(dobValue);\r\n");
      out.write("		const today = new Date();\r\n");
      out.write("		let age = today.getFullYear() - dob.getFullYear();\r\n");
      out.write("		const monthDiff = today.getMonth() - dob.getMonth();\r\n");
      out.write("		const dayDiff = today.getDate() - dob.getDate();\r\n");
      out.write("\r\n");
      out.write("		// Adjust for not yet reached birthday\r\n");
      out.write("		if (monthDiff < 0 || (monthDiff === 0 && dayDiff < 0)) {\r\n");
      out.write("			age--;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (age < 26) {\r\n");
      out.write("			dobError.textContent = \"Doctor must be at least 26 years old.\";\r\n");
      out.write("			dobInput.classList.add(\"is-invalid\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (age > 75) {\r\n");
      out.write("			dobError.textContent = \"Doctor's age cannot be more than 75 years.\";\r\n");
      out.write("			dobInput.classList.add(\"is-invalid\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		dobInput.classList.add(\"is-valid\");\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	 function validatePassword() {\r\n");
      out.write("	        const passwordInput = document.getElementById(\"password\");\r\n");
      out.write("	        const passwordError = document.getElementById(\"passwordError\");\r\n");
      out.write("	        const passwordValue = passwordInput.value.trim();\r\n");
      out.write("\r\n");
      out.write("	        // Password regex pattern\r\n");
      out.write("	        const passwordPattern = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$/;\r\n");
      out.write("\r\n");
      out.write("	        // Reset messages and styles\r\n");
      out.write("	        passwordError.textContent = \"\";\r\n");
      out.write("	        passwordInput.classList.remove(\"is-invalid\", \"is-valid\");\r\n");
      out.write("\r\n");
      out.write("	        // Empty check\r\n");
      out.write("	        if (passwordValue === \"\") {\r\n");
      out.write("	            passwordError.textContent = \"Password is required.\";\r\n");
      out.write("	            passwordInput.classList.add(\"is-invalid\");\r\n");
      out.write("	            return false;\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	        // Pattern check\r\n");
      out.write("	        if (!passwordPattern.test(passwordValue)) {\r\n");
      out.write("	            passwordError.textContent =\r\n");
      out.write("	                \"Password must be at least 8 characters and include uppercase, lowercase, number, and special character.\";\r\n");
      out.write("	            passwordInput.classList.add(\"is-invalid\");\r\n");
      out.write("	            return false;\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	        // Valid case\r\n");
      out.write("	        passwordInput.classList.add(\"is-valid\");\r\n");
      out.write("	        return true;\r\n");
      out.write("	    }\r\n");
      out.write("	 \r\n");
      out.write("	document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("		const form = document.querySelector(\"form\");\r\n");
      out.write("		const emailField = document.getElementById(\"email\");\r\n");
      out.write("		const dobField = document.getElementById(\"dateOfBirth\");\r\n");
      out.write("\r\n");
      out.write("		// Prevent selecting future dates and attach DOB listener\r\n");
      out.write("		if (dobField) {\r\n");
      out.write("			const today = new Date().toISOString().split(\"T\")[0];\r\n");
      out.write("			dobField.setAttribute(\"max\", today);\r\n");
      out.write("			dobField.addEventListener(\"change\", validateDOB);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (emailField) {\r\n");
      out.write("			emailField.addEventListener(\"input\", validateEmail);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (form) {\r\n");
      out.write("			form.addEventListener(\"submit\", function(e) {\r\n");
      out.write("				const validEmail = validateEmail();\r\n");
      out.write("				const validDOB = validateDOB();\r\n");
      out.write("\r\n");
      out.write("				if (!validEmail || !validDOB) {\r\n");
      out.write("					e.preventDefault(); // stop form submission\r\n");
      out.write("					if (!validDOB)\r\n");
      out.write("						dobField.focus();\r\n");
      out.write("					if (!validEmail)\r\n");
      out.write("						emailField.focus();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Admin Navbar - Dark Theme -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark sticky-top\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <!-- UPDATED: Restored main site logo -->\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-hospital me-2\"></i> Doctor Patient Portal\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("            data-bs-toggle=\"collapse\" data-bs-target=\"#adminNavbar\"\r\n");
      out.write("            aria-controls=\"adminNavbar\" aria-expanded=\"false\"\r\n");
      out.write("            aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"adminNavbar\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("                    aria-current=\"page\" href=\"index.jsp\"><i class=\"fa fa-home me-1\"></i> HOME</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("                    aria-current=\"page\" href=\"doctor.jsp\"><i\r\n");
      out.write("                        class=\"fa-solid fa-user-doctor me-1\"></i> DOCTOR</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("                    aria-current=\"page\" href=\"view_doctor.jsp\"><i\r\n");
      out.write("                        class=\"fa-solid fa-list me-1\"></i> VIEW DOCTOR</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("                    aria-current=\"page\" href=\"patient.jsp\"><i\r\n");
      out.write("                        class=\"fa-solid fa-user-injured me-1\"></i> PATIENT APPOINTMENTS</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("            <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <!-- Check if Admin is logged in -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <!-- If admin is not in session, redirect to login -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Form Wrapper for Centering -->\r\n");
      out.write("	<div class=\"form-wrapper\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!-- Centered column layout, responsive collapse on mobile -->\r\n");
      out.write("				<div class=\"col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3\">\r\n");
      out.write("					<div class=\"card my-card\">\r\n");
      out.write("						<div class=\"card-body p-4 p-lg-5\">\r\n");
      out.write("							<h3 class=\"text-center mb-4\">Add Doctor</h3>\r\n");
      out.write("\r\n");
      out.write("							<!-- Message Handling -->\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Add Doctor Form -->\r\n");
      out.write("							<form action=\"../addDoctor\" method=\"post\">\r\n");
      out.write("								<div class=\"row g-3\">\r\n");
      out.write("									<div class=\"col-12\">\r\n");
      out.write("										<label class=\"form-label\">Full Name</label> <input\r\n");
      out.write("											name=\"fullName\" type=\"text\" placeholder=\"Enter full name\"\r\n");
      out.write("											class=\"form-control\" required pattern=\"^[A-Za-z\\s]{2,40}$\"\r\n");
      out.write("											maxlength=\"40\"\r\n");
      out.write("											title=\"Full Name must be 2-40 letters and spaces only (no numbers or special characters)\"\r\n");
      out.write("											oninput=\"this.value = this.value.replace(/[^A-Za-z ]/g, '')\">\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-md-6 col-12\">\r\n");
      out.write("										<label class=\"form-label\">Date of Birth</label> <input\r\n");
      out.write("											required id=\"dateOfBirth\" name=\"dateOfBirth\" type=\"date\"\r\n");
      out.write("											class=\"form-control\">\r\n");
      out.write("										<div id=\"dobError\" class=\"text-danger mt-1\"\r\n");
      out.write("											style=\"font-size: 0.9em;\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-md-6 col-12\">\r\n");
      out.write("										<label class=\"form-label\">Qualification</label> <input\r\n");
      out.write("											name=\"qualification\" type=\"text\"\r\n");
      out.write("											placeholder=\"Enter qualification (e.g., MBBS, MD)\"\r\n");
      out.write("											class=\"form-control\" required>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-6 col-12\">\r\n");
      out.write("										<label class=\"form-label\">Specialist</label> <select\r\n");
      out.write("											class=\"form-select\" name=\"specialist\" required>\r\n");
      out.write("											<option disabled selected value=\"\">---Select\r\n");
      out.write("												Specialist---</option>\r\n");
      out.write("											");

											// --- START: Backend Logic (DO NOT DISTURB) ---
											SpecialistDAO spDAO = new SpecialistDAO(DBConnection.getConn());
											List<Specialist> spList = spDAO.getAllSpecialist();
											for (Specialist s : spList) {
												// --- END: Backend Logic ---
											
      out.write("\r\n");
      out.write("											<option>");
      out.print(s.getSpecialistName());
      out.write("</option>\r\n");
      out.write("											");

											}
											
      out.write("\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-6 col-12\">\r\n");
      out.write("										<label class=\"form-label\">Email Address</label> <input\r\n");
      out.write("											required id=\"email\" name=\"email\" type=\"email\"\r\n");
      out.write("											placeholder=\"Enter Email\" class=\"form-control\" maxlength=\"75\"\r\n");
      out.write("											title=\"Please enter a valid email address (e.g., user@example.com)\">\r\n");
      out.write("										<div id=\"emailError\" class=\"text-danger mt-1\"\r\n");
      out.write("											style=\"font-size: 0.9em;\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-md-6 col-12\">\r\n");
      out.write("										<label class=\"form-label\">Phone</label> <input name=\"phone\"\r\n");
      out.write("											required type=\"tel\" placeholder=\"Enter 10-digit number\"\r\n");
      out.write("											class=\"form-control\" pattern=\"^\\d{10}$\" maxlength=\"10\"\r\n");
      out.write("											title=\"Please enter a valid 10-digit mobile number\"\r\n");
      out.write("											oninput=\"this.value = this.value.replace(/[^0-9]/g, '');\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-6 col-12\">\r\n");
      out.write("										<label class=\"form-label\" for=\"password\">Password</label> <input\r\n");
      out.write("											id=\"password\" name=\"password\" type=\"password\"\r\n");
      out.write("											placeholder=\"Enter password\" class=\"form-control\" required\r\n");
      out.write("											oninput=\"validatePassword()\"> <small\r\n");
      out.write("											id=\"passwordError\" class=\"text-danger\"></small>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-12 mt-4\">\r\n");
      out.write("										<button type=\"submit\" class=\"btn btn-primary w-100\">Register\r\n");
      out.write("											Doctor</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /admin/navbar.jsp(37,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty adminObj }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                     <li class=\"nav-item dropdown\">\r\n");
        out.write("                        <a class=\"nav-link dropdown-toggle active\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
        out.write("                           <i class=\"fa-solid fa-user-shield me-1\"></i> Admin\r\n");
        out.write("                        </a>\r\n");
        out.write("                        <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">\r\n");
        out.write("                            <li><a class=\"dropdown-item\" href=\"../adminLogout\"><i class=\"fa-solid fa-right-from-bracket me-2\"></i> Logout</a></li>\r\n");
        out.write("                        </ul>\r\n");
        out.write("                    </li>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /admin/navbar.jsp(49,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty adminObj }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                    ");
        if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /admin/navbar.jsp(50,20) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f0.setUrl("../admin_login.jsp");
    int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
    if (_jspx_th_c_005fredirect_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /admin/doctor.jsp(296,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty successMsg }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("								<div class=\"alert alert-success text-center\" role=\"alert\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${successMsg}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\r\n");
        out.write("								");
        if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("							");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fremove_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /admin/doctor.jsp(298,8) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f0.setVar("successMsg");
    // /admin/doctor.jsp(298,8) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f0.setScope("session");
    int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
    if (_jspx_th_c_005fremove_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /admin/doctor.jsp(300,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMsg }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("								<div class=\"alert alert-danger text-center\" role=\"alert\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\r\n");
        out.write("								");
        if (_jspx_meth_c_005fremove_005f1(_jspx_th_c_005fif_005f3, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("							");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f1 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    _jspx_th_c_005fremove_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fremove_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
    // /admin/doctor.jsp(302,8) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f1.setVar("errorMsg");
    // /admin/doctor.jsp(302,8) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f1.setScope("session");
    int _jspx_eval_c_005fremove_005f1 = _jspx_th_c_005fremove_005f1.doStartTag();
    if (_jspx_th_c_005fremove_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f1);
    return false;
  }
}
