/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.43
 * Generated at: 2025-11-14 13:24:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.doctor;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.hms.dao.AppointmentDAO;
import com.hms.entity.Doctor;
import com.hms.db.DBConnection;
import com.hms.dao.DoctorDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/component/allcss.jsp", Long.valueOf(1763046081998L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1754389174666L));
    _jspx_dependants.put("/doctor/navbar.jsp", Long.valueOf(1763124003646L));
    _jspx_dependants.put("jar:file:/Z:/project_workspace_new/Doctor-Patient-Portal-AdvanceJavaWebProject-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Doctor-Patient-Portal/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.hms.db.DBConnection");
    _jspx_imports_classes.add("com.hms.entity.Doctor");
    _jspx_imports_classes.add("com.hms.dao.DoctorDAO");
    _jspx_imports_classes.add("com.hms.dao.AppointmentDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Doctor Dashboard</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("    href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("    crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome CSS (for icons) -->\r\n");
      out.write("<link\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\"\r\n");
      out.write("    integrity=\"sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==\"\r\n");
      out.write("    crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script\r\n");
      out.write("    src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Global Custom Styles -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       THEME COLORS & VARIABLES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    :root {\r\n");
      out.write("        --primary-color: #4568dc;\r\n");
      out.write("        --primary-hover: #3654b3;\r\n");
      out.write("        --accent-color: #00c6ff;\r\n");
      out.write("        --light-bg: #f8f9fa;\r\n");
      out.write("        --dark-text: #2d2d2d;\r\n");
      out.write("        --card-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        --transition-speed: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif;\r\n");
      out.write("        background-color: var(--light-bg);\r\n");
      out.write("        color: var(--dark-text);\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        REUSABLE CLASSES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-bg-color { background-color: var(--primary-color) !important; }\r\n");
      out.write("    .myP-color { color: var(--primary-color) !important; }\r\n");
      out.write("    .my-hover:hover { color: var(--primary-hover) !important; }\r\n");
      out.write("\r\n");
      out.write("    /* Button Enhancements */\r\n");
      out.write("    .btn.my-bg-color {\r\n");
      out.write("        background-color: var(--primary-color);\r\n");
      out.write("        border-color: var(--primary-color);\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: background-color var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("    .btn.my-bg-color:hover {\r\n");
      out.write("        background-color: var(--primary-hover);\r\n");
      out.write("        border-color: var(--primary-hover);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       NAVBAR STYLING\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .navbar {\r\n");
      out.write("        box-shadow: 0 2px 6px rgba(0,0,0,0.1);\r\n");
      out.write("        background: linear-gradient(90deg, var(--primary-color), var(--accent-color));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .navbar-brand {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #fff !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .nav-link, .navbar .dropdown-toggle {\r\n");
      out.write("        color: #fff !important;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: color var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .nav-link:hover {\r\n");
      out.write("        color: #e2e2e2 !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-menu {\r\n");
      out.write("        border: none;\r\n");
      out.write("        box-shadow: var(--card-shadow);\r\n");
      out.write("        border-radius: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        FORMS & INPUTS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .form-control, .form-select {\r\n");
      out.write("        border-radius: 0.5rem;\r\n");
      out.write("        transition: all var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control:focus, .form-select:focus {\r\n");
      out.write("        border-color: var(--primary-color);\r\n");
      out.write("        box-shadow: 0 0 0 0.25rem rgba(69,104,220,0.25);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        CARDS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-card {\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 0.75rem;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        box-shadow: var(--card-shadow);\r\n");
      out.write("        transition: transform 0.2s ease, box-shadow 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .my-card:hover {\r\n");
      out.write("        transform: translateY(-3px);\r\n");
      out.write("        box-shadow: 0 8px 18px rgba(0, 0, 0, 0.12);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        TABLE STYLING\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .table thead {\r\n");
      out.write("        background-color: var(--primary-color);\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table th {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        BACKGROUND UTILITIES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-bg-img {\r\n");
      out.write("        background: linear-gradient(rgba(0, 0, 0, .4), rgba(0, 0, 0, .4)),\r\n");
      out.write("                    url(\"img/hospital1.jpg\") center/cover no-repeat;\r\n");
      out.write("        height: 25vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-shadow: 0 2px 4px rgba(0,0,0,0.6);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       LOGIN & SIGNUP PAGES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .login-container {\r\n");
      out.write("        min-height: 90vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        padding: 2rem 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-card {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 450px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       RESPONSIVENESS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .navbar .nav-link { font-size: 0.95rem; }\r\n");
      out.write("        .my-bg-img { height: 20vh; background-position: top center; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("        .login-card { padding: 1rem; }\r\n");
      out.write("        .my-bg-img { height: 18vh; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        ANIMATION HELPERS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .fade-in {\r\n");
      out.write("        animation: fadeIn 0.8s ease-in-out forwards;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeIn {\r\n");
      out.write("        from { opacity: 0; transform: translateY(10px); }\r\n");
      out.write("        to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* === PAGE BASE AND BACKGROUND === */\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8faff; /* Very light, clean base */\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding-top: 70px; /* CRUCIAL: Space for fixed navbar */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Blurred Background Image */\r\n");
      out.write("body::before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	/* Assuming the path for the background image is correct */\r\n");
      out.write("	background: url('../img/hospital1.jpg') center center/cover no-repeat fixed;\r\n");
      out.write("	filter: blur(8px) brightness(1.05); /* Strong blur and slightly brighter */\r\n");
      out.write("	opacity: 0.9;\r\n");
      out.write("	z-index: -1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Main Content Wrapper (Container for form) */\r\n");
      out.write(".dashboard-wrapper {\r\n");
      out.write("	flex-grow: 1; /* Allows it to take up available space */\r\n");
      out.write("	padding: 30px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Killer UI Card Style (Glass Morphism) */\r\n");
      out.write(".my-card {\r\n");
      out.write("	/* Glass effect background */\r\n");
      out.write("	background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("	backdrop-filter: blur(15px);\r\n");
      out.write("	-webkit-backdrop-filter: blur(15px);\r\n");
      out.write("	border-radius: 1.5rem;\r\n");
      out.write("	border: 1px solid rgba(220, 220, 220, 0.7);\r\n");
      out.write("	box-shadow: 0 15px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	height: 100%; /* Important for equal height in flex layout */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".my-card:hover {\r\n");
      out.write("	transform: translateY(-5px);\r\n");
      out.write("	box-shadow: 0 20px 50px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dashboard Header Styling */\r\n");
      out.write(".dashboard-header {\r\n");
      out.write("	color: #1e88e5; /* Primary blue for main title */\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("	letter-spacing: 0.5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".welcome-message {\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	color: #555;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Card Content Styling */\r\n");
      out.write(".my-card h4 {\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	font-size: 1.3rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".my-card .fs-1 {\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Custom Card Colors (Tailored for dashboard status) */\r\n");
      out.write(".card-appointments i, .card-appointments .fs-1 {\r\n");
      out.write("	color: #1e88e5; /* Primary Blue */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-pending i, .card-pending .fs-1 {\r\n");
      out.write("	color: #ff9800; /* Orange/Warning */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-success i, .card-success .fs-1 {\r\n");
      out.write("	color: #4CAF50; /* Success Green */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive adjustments */\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	.dashboard-wrapper {\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	.my-card {\r\n");
      out.write("		padding: 1.5rem !important;\r\n");
      out.write("	}\r\n");
      out.write("	.dashboard-header {\r\n");
      out.write("		font-size: 1.8rem;\r\n");
      out.write("	}\r\n");
      out.write("	.welcome-message {\r\n");
      out.write("		font-size: 1rem;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Doctor Navbar - Green Theme -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-success fixed-top\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <!-- Main site logo/name -->\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("             <i class=\"fa-sharp fa-solid fa-hospital me-2\"></i> Doctor Patient Portal\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("            data-bs-toggle=\"collapse\" data-bs-target=\"#doctorNavbar\"\r\n");
      out.write("            aria-controls=\"doctorNavbar\" aria-expanded=\"false\"\r\n");
      out.write("            aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"doctorNavbar\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"index.jsp\"><i class=\"fa fa-home me-1\"></i> HOME</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Link to Appointment History page -->\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"patient.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-calendar-alt me-1\"></i> APPOINTMENTS\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <!-- Check if Doctor is logged in -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <!-- If doctor is not in session, redirect to login -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Check if doctor is logged in -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"dashboard-wrapper\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-12 text-center mb-5\">\r\n");
      out.write("					<h2 class=\"dashboard-header\">Doctor Dashboard</h2>\r\n");
      out.write("					");

						// Get logged-in Doctor object
						Doctor currentLoginDoctor = (Doctor) session.getAttribute("doctorObj");
						// Initialize DoctorDAO (kept for existing structure)
						DoctorDAO docDAO = new DoctorDAO(DBConnection.getConn());
					
      out.write("\r\n");
      out.write("					<h4 class=\"welcome-message\">Welcome, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${doctorObj.fullName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\r\n");
      out.write("					");

						// --- START: Logic for Appointment Counts (New/Updated logic) ---
						int totalCount = 0;
						int pendingCount = 0;
						int successCount = 0;
						
						// Check if doctor is logged in before proceeding with DB calls
						if (currentLoginDoctor != null) {
							// 1. Initialize AppointmentDAO for counting
							AppointmentDAO appDAO = new AppointmentDAO(DBConnection.getConn());
							int doctorId = currentLoginDoctor.getId();
							
							// 2. Calculate the counts using the new methods
							totalCount = appDAO.countTotalAppointmentByDoctorId(doctorId);
							pendingCount = appDAO.countPendingAppointmentByDoctorId(doctorId);
							successCount = appDAO.countSuccessfulAppointmentByDoctorId(doctorId);
						}
						// --- END: Logic for Appointment Counts ---
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row g-4 d-flex justify-content-center\">\r\n");
      out.write("			\r\n");
      out.write("				<!-- CARD 1: Total Appointments -->\r\n");
      out.write("				<div class=\"col-12 col-sm-6 col-md-4\">\r\n");
      out.write("					<div class=\"card my-card card-appointments p-3\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<i class=\"fa-solid fa-calendar-check fa-3x\"></i>\r\n");
      out.write("							<h4>Total Appointments</h4>\r\n");
      out.write("							<h5 class=\"fs-1\">\r\n");
      out.write("								");
      out.print( totalCount );
      out.write("\r\n");
      out.write("							</h5>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<!-- CARD 2: Pending Appointments -->\r\n");
      out.write("				<div class=\"col-12 col-sm-6 col-md-4\">\r\n");
      out.write("					<div class=\"card my-card card-pending p-3\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<i class=\"fa-solid fa-clock fa-3x\"></i>\r\n");
      out.write("							<h4>Pending Appointments</h4>\r\n");
      out.write("							<h5 class=\"fs-1\">\r\n");
      out.write("								");
      out.print( pendingCount );
      out.write("\r\n");
      out.write("							</h5>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<!-- CARD 3: Successful Consults -->\r\n");
      out.write("				<div class=\"col-12 col-sm-6 col-md-4\">\r\n");
      out.write("					<div class=\"card my-card card-success p-3\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<i class=\"fa-solid fa-heart-circle-check fa-3x\"></i>\r\n");
      out.write("							<h4>Successful Consults</h4>\r\n");
      out.write("							<h5 class=\"fs-1\">\r\n");
      out.write("								");
      out.print( successCount );
      out.write("\r\n");
      out.write("							</h5>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- Added a quick link for navigation -->\r\n");
      out.write("			<div class=\"row mt-5\">\r\n");
      out.write("			    <div class=\"col-12 text-center\">\r\n");
      out.write("			        <a href=\"patient.jsp\" class=\"btn btn-lg btn-outline-primary\"\r\n");
      out.write("			           style=\"border-radius: 1rem; font-weight: 600;\">\r\n");
      out.write("			            View All Appointments\r\n");
      out.write("			        </a>\r\n");
      out.write("			    </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /doctor/navbar.jsp(36,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty doctorObj }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                    <li class=\"nav-item dropdown\">\r\n");
        out.write("                        <a class=\"nav-link dropdown-toggle active\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
        out.write("                            <i class=\"fa-solid fa-circle-user me-1\"></i> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${doctorObj.fullName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("                        </a>\r\n");
        out.write("                        <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">\r\n");
        out.write("                            <li><a class=\"dropdown-item\" href=\"edit_profile.jsp\"><i class=\"fa-solid fa-user-edit me-2\"></i> Edit Profile</a></li>\r\n");
        out.write("                            <li><hr class=\"dropdown-divider\"></li>\r\n");
        out.write("                            <li><a class=\"dropdown-item\" href=\"../doctorLogout\"><i class=\"fa-solid fa-right-from-bracket me-2\"></i> Logout</a></li>\r\n");
        out.write("                        </ul>\r\n");
        out.write("                    </li>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /doctor/navbar.jsp(50,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty doctorObj }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                    ");
        if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /doctor/navbar.jsp(51,20) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f0.setUrl("../doctor_login.jsp");
    int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
    if (_jspx_th_c_005fredirect_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /doctor/index.jsp(132,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty doctorObj }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("		");
        if (_jspx_meth_c_005fredirect_005f1(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f1 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /doctor/index.jsp(133,2) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f1.setUrl("../doctor_login.jsp");
    int _jspx_eval_c_005fredirect_005f1 = _jspx_th_c_005fredirect_005f1.doStartTag();
    if (_jspx_th_c_005fredirect_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f1);
    return false;
  }
}
