/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.43
 * Generated at: 2025-11-14 13:18:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.hms.db.DBConnection;
import java.sql.Connection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/component/allcss.jsp", Long.valueOf(1763046081998L));
    _jspx_dependants.put("/component/footer.jsp", Long.valueOf(1762928471330L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1754389174666L));
    _jspx_dependants.put("/component/navbar.jsp", Long.valueOf(1763043036559L));
    _jspx_dependants.put("jar:file:/Z:/project_workspace_new/Doctor-Patient-Portal-AdvanceJavaWebProject-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Doctor-Patient-Portal/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.hms.db.DBConnection");
    _jspx_imports_classes.add("java.sql.Connection");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<title>Home | Doctor Patient Portal</title>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("    href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("    crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome CSS (for icons) -->\r\n");
      out.write("<link\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\"\r\n");
      out.write("    integrity=\"sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==\"\r\n");
      out.write("    crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script\r\n");
      out.write("    src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Global Custom Styles -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       THEME COLORS & VARIABLES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    :root {\r\n");
      out.write("        --primary-color: #4568dc;\r\n");
      out.write("        --primary-hover: #3654b3;\r\n");
      out.write("        --accent-color: #00c6ff;\r\n");
      out.write("        --light-bg: #f8f9fa;\r\n");
      out.write("        --dark-text: #2d2d2d;\r\n");
      out.write("        --card-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        --transition-speed: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif;\r\n");
      out.write("        background-color: var(--light-bg);\r\n");
      out.write("        color: var(--dark-text);\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        REUSABLE CLASSES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-bg-color { background-color: var(--primary-color) !important; }\r\n");
      out.write("    .myP-color { color: var(--primary-color) !important; }\r\n");
      out.write("    .my-hover:hover { color: var(--primary-hover) !important; }\r\n");
      out.write("\r\n");
      out.write("    /* Button Enhancements */\r\n");
      out.write("    .btn.my-bg-color {\r\n");
      out.write("        background-color: var(--primary-color);\r\n");
      out.write("        border-color: var(--primary-color);\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: background-color var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("    .btn.my-bg-color:hover {\r\n");
      out.write("        background-color: var(--primary-hover);\r\n");
      out.write("        border-color: var(--primary-hover);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       NAVBAR STYLING\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .navbar {\r\n");
      out.write("        box-shadow: 0 2px 6px rgba(0,0,0,0.1);\r\n");
      out.write("        background: linear-gradient(90deg, var(--primary-color), var(--accent-color));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .navbar-brand {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #fff !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .nav-link, .navbar .dropdown-toggle {\r\n");
      out.write("        color: #fff !important;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: color var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .nav-link:hover {\r\n");
      out.write("        color: #e2e2e2 !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-menu {\r\n");
      out.write("        border: none;\r\n");
      out.write("        box-shadow: var(--card-shadow);\r\n");
      out.write("        border-radius: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        FORMS & INPUTS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .form-control, .form-select {\r\n");
      out.write("        border-radius: 0.5rem;\r\n");
      out.write("        transition: all var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control:focus, .form-select:focus {\r\n");
      out.write("        border-color: var(--primary-color);\r\n");
      out.write("        box-shadow: 0 0 0 0.25rem rgba(69,104,220,0.25);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        CARDS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-card {\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 0.75rem;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        box-shadow: var(--card-shadow);\r\n");
      out.write("        transition: transform 0.2s ease, box-shadow 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .my-card:hover {\r\n");
      out.write("        transform: translateY(-3px);\r\n");
      out.write("        box-shadow: 0 8px 18px rgba(0, 0, 0, 0.12);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        TABLE STYLING\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .table thead {\r\n");
      out.write("        background-color: var(--primary-color);\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table th {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        BACKGROUND UTILITIES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-bg-img {\r\n");
      out.write("        background: linear-gradient(rgba(0, 0, 0, .4), rgba(0, 0, 0, .4)),\r\n");
      out.write("                    url(\"img/hospital1.jpg\") center/cover no-repeat;\r\n");
      out.write("        height: 25vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-shadow: 0 2px 4px rgba(0,0,0,0.6);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       LOGIN & SIGNUP PAGES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .login-container {\r\n");
      out.write("        min-height: 90vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        padding: 2rem 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-card {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 450px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       RESPONSIVENESS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .navbar .nav-link { font-size: 0.95rem; }\r\n");
      out.write("        .my-bg-img { height: 20vh; background-position: top center; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("        .login-card { padding: 1rem; }\r\n");
      out.write("        .my-bg-img { height: 18vh; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        ANIMATION HELPERS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .fade-in {\r\n");
      out.write("        animation: fadeIn 0.8s ease-in-out forwards;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeIn {\r\n");
      out.write("        from { opacity: 0; transform: translateY(10px); }\r\n");
      out.write("        to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ===== Custom Styles ===== -->\r\n");
      out.write("	<style>\r\n");
      out.write("		body {\r\n");
      out.write("			background: #f8f9fa;\r\n");
      out.write("			color: #212529;\r\n");
      out.write("			font-family: 'Poppins', sans-serif;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.myP-color {\r\n");
      out.write("			color: #0d6efd;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.my-card {\r\n");
      out.write("			border: none;\r\n");
      out.write("			border-radius: 1rem;\r\n");
      out.write("			box-shadow: 0 4px 15px rgba(0, 0, 0, 0.08);\r\n");
      out.write("			transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("			background: #fff;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.my-card:hover {\r\n");
      out.write("			transform: translateY(-5px);\r\n");
      out.write("			box-shadow: 0 6px 25px rgba(0, 0, 0, 0.12);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.card-body h4 {\r\n");
      out.write("			font-weight: 600;\r\n");
      out.write("			margin-bottom: 0.6rem;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		h2.section-title {\r\n");
      out.write("			font-size: 2rem;\r\n");
      out.write("			font-weight: 700;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			color: #0d6efd;\r\n");
      out.write("			position: relative;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		h2.section-title::after {\r\n");
      out.write("			content: \"\";\r\n");
      out.write("			display: block;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			height: 4px;\r\n");
      out.write("			background: #0d6efd;\r\n");
      out.write("			margin: 10px auto 0;\r\n");
      out.write("			border-radius: 2px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/* ===== Carousel Fix ===== */\r\n");
      out.write("		.carousel-inner img {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: auto;\r\n");
      out.write("			max-height: 550px;\r\n");
      out.write("			object-fit: contain;\r\n");
      out.write("			border-radius: 0;\r\n");
      out.write("			background-color: #fff;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		@media (max-width: 992px) {\r\n");
      out.write("			.carousel-inner img {\r\n");
      out.write("				max-height: 400px;\r\n");
      out.write("				object-fit: cover;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.team-card {\r\n");
      out.write("			border: none;\r\n");
      out.write("			border-radius: 15px;\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("			box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("			transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("			background: #fff;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.team-card:hover {\r\n");
      out.write("			transform: translateY(-8px);\r\n");
      out.write("			box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.team-card img {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: auto;\r\n");
      out.write("			object-fit: cover;\r\n");
      out.write("			transition: transform 0.4s ease;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.team-card:hover img {\r\n");
      out.write("			transform: scale(1.05);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.card-body {\r\n");
      out.write("			padding: 20px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.footer {\r\n");
      out.write("			background: linear-gradient(135deg, #0d6efd, #6610f2);\r\n");
      out.write("			color: #fff;\r\n");
      out.write("			padding: 2rem 0;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/* ===== Responsive ===== */\r\n");
      out.write("		@media (max-width: 768px) {\r\n");
      out.write("			h2.section-title {\r\n");
      out.write("				font-size: 1.6rem;\r\n");
      out.write("			}\r\n");
      out.write("			.card-body h4 {\r\n");
      out.write("				font-size: 1rem;\r\n");
      out.write("			}\r\n");
      out.write("			.carousel-inner img {\r\n");
      out.write("				max-height: 300px;\r\n");
      out.write("			}\r\n");
      out.write("			.card-body h5 {\r\n");
      out.write("				font-size: 1.1rem;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		@media (max-width: 576px) {\r\n");
      out.write("			.card-body p {\r\n");
      out.write("				font-size: 0.9rem;\r\n");
      out.write("			}\r\n");
      out.write("			.card-body {\r\n");
      out.write("				padding: 15px;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	<!-- ===== End Custom Styles ===== -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* ====== KILLER BLUE THEME NAVBAR ====== */\r\n");
      out.write(".blue-navbar {\r\n");
      out.write("  background: linear-gradient(90deg, #007bff 0%, #0056b3 100%);\r\n");
      out.write("  box-shadow: 0 4px 18px rgba(0, 91, 255, 0.35);\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  padding: 0.6rem 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blue-navbar.scrolled {\r\n");
      out.write("  background: linear-gradient(90deg, #0056b3 0%, #003d99 100%);\r\n");
      out.write("  box-shadow: 0 6px 25px rgba(0, 0, 0, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Brand Styling */\r\n");
      out.write(".blue-navbar .navbar-brand {\r\n");
      out.write("  font-weight: 800;\r\n");
      out.write("  font-size: 1.3rem;\r\n");
      out.write("  color: #ffffff !important;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  gap: 8px;\r\n");
      out.write("  text-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nav Links */\r\n");
      out.write(".blue-navbar .nav-link {\r\n");
      out.write("  color: #ffffff !important;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  letter-spacing: 0.5px;\r\n");
      out.write("  padding: 0.6rem 1.2rem;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("  margin: 0 2px;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blue-navbar .nav-link:hover {\r\n");
      out.write("  background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("  box-shadow: 0 0 10px rgba(255, 255, 255, 0.3);\r\n");
      out.write("  transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Animated underline effect */\r\n");
      out.write(".blue-navbar .nav-link::after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 6px;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write(".blue-navbar .nav-link:hover::after {\r\n");
      out.write("  width: 60%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dropdown */\r\n");
      out.write(".blue-navbar .dropdown-menu {\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2);\r\n");
      out.write("  animation: fadeIn 0.25s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".blue-navbar .dropdown-item {\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  color: #333;\r\n");
      out.write("  border-radius: 6px;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".blue-navbar .dropdown-item:hover {\r\n");
      out.write("  background: linear-gradient(90deg, #007bff, #0056b3);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  transform: translateX(4px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Toggler */\r\n");
      out.write(".navbar-toggler {\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("  border-radius: 6px;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".navbar-toggler:hover {\r\n");
      out.write("  background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Animation */\r\n");
      out.write("@keyframes fadeIn {\r\n");
      out.write("  from { opacity: 0; transform: translateY(-10px); }\r\n");
      out.write("  to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media (max-width: 992px) {\r\n");
      out.write("  .blue-navbar .nav-link {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin: 6px 0;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark sticky-top blue-navbar\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("      <i class=\"fa-solid fa-hospital\"></i> Doctor Patient Portal\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("      data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("      aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("      aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Guest -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- User -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Doctor/Admin Redirect -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener(\"scroll\", () => {\r\n");
      out.write("  const nav = document.querySelector(\".blue-navbar\");\r\n");
      out.write("  if (window.scrollY > 10) nav.classList.add(\"scrolled\");\r\n");
      out.write("  else nav.classList.remove(\"scrolled\");\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ===== Carousel ===== -->\r\n");
      out.write("	<div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("		<div class=\"carousel-indicators\">\r\n");
      out.write("			<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\"\r\n");
      out.write("				class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("			<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\"\r\n");
      out.write("				aria-label=\"Slide 2\"></button>\r\n");
      out.write("			<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\"\r\n");
      out.write("				aria-label=\"Slide 3\"></button>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"carousel-inner\">\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<img src=\"img/doctor_1.png\" class=\"d-block w-100\" alt=\"Doctor\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item active\">\r\n");
      out.write("				<img src=\"img/docktor_02.png\" class=\"d-block w-100\" alt=\"Doctor\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<img src=\"img/hospital4.png\" class=\"d-block w-100\" alt=\"Hospital\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("			data-bs-slide=\"prev\">\r\n");
      out.write("			<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("			<span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("			data-bs-slide=\"next\">\r\n");
      out.write("			<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("			<span class=\"visually-hidden\">Next</span>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ===== End Carousel ===== -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ===== Key Features ===== -->\r\n");
      out.write("	<div class=\"container py-5\">\r\n");
      out.write("		<h2 class=\"section-title mb-5\">Key Features of Our Doctor Patient Portal</h2>\r\n");
      out.write("		<div class=\"row g-4 align-items-center\">\r\n");
      out.write("			<div class=\"col-md-8\">\r\n");
      out.write("				<div class=\"row g-4\">\r\n");
      out.write("					<div class=\"col-md-6\">\r\n");
      out.write("						<div class=\"card my-card h-100\">\r\n");
      out.write("							<div class=\"card-body p-4\">\r\n");
      out.write("								<h4 class=\"myP-color\">11000+ Healing Hands</h4>\r\n");
      out.write("								<p class=\"text-secondary\">Largest network of the world’s finest and brightest medical\r\n");
      out.write("									experts who provide compassionate care.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6\">\r\n");
      out.write("						<div class=\"card my-card h-100\">\r\n");
      out.write("							<div class=\"card-body p-4\">\r\n");
      out.write("								<h4 class=\"myP-color\">Most Advanced Healthcare</h4>\r\n");
      out.write("								<p class=\"text-secondary\">We have pioneered ground-breaking healthcare technologies\r\n");
      out.write("									and innovative treatments nationwide.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6\">\r\n");
      out.write("						<div class=\"card my-card h-100\">\r\n");
      out.write("							<div class=\"card-body p-4\">\r\n");
      out.write("								<h4 class=\"myP-color\">Best Clinical Outcomes</h4>\r\n");
      out.write("								<p class=\"text-secondary\">Leveraging medical expertise & technology for best-in-class\r\n");
      out.write("									clinical outcomes with personalized care.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6\">\r\n");
      out.write("						<div class=\"card my-card h-100\">\r\n");
      out.write("							<div class=\"card-body p-4\">\r\n");
      out.write("								<h4 class=\"myP-color\">500+ Pharmacies</h4>\r\n");
      out.write("								<p class=\"text-secondary\">Our trusted pharmacy network has over 500+ outlets across\r\n");
      out.write("									the nation to ensure medicine availability.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Image Column -->\r\n");
      out.write("			<div class=\"col-md-4 text-center\">\r\n");
      out.write("				<img src=\"img/doctor_3.jpg\" class=\"img-fluid rounded shadow-sm\"\r\n");
      out.write("					alt=\"Doctor Image\" style=\"height: 100%; object-fit: cover;\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ===== End Key Features ===== -->\r\n");
      out.write("\r\n");
      out.write("	<hr class=\"my-5\">\r\n");
      out.write("\r\n");
      out.write("	<!-- ===== Our Team ===== -->\r\n");
      out.write("	<div class=\"container pb-5 pt-3\">\r\n");
      out.write("		<h2 class=\"section-title mb-5\">Our Expert Team</h2>\r\n");
      out.write("		<div class=\"row g-4 justify-content-center\">\r\n");
      out.write("			<div class=\"col-12 col-sm-6 col-md-4 col-lg-3\">\r\n");
      out.write("				<div class=\"card my-card team-card text-center\">\r\n");
      out.write("					<img src=\"img/doc1.png\" class=\"card-img-top\" alt=\"Dr. John\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<h5 class=\"fw-bold myP-color\">Dr. John</h5>\r\n");
      out.write("						<p class=\"text-secondary\">(CEO & Chairman)</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-12 col-sm-6 col-md-4 col-lg-3\">\r\n");
      out.write("				<div class=\"card my-card team-card text-center\">\r\n");
      out.write("					<img src=\"img/doc2.png\" class=\"card-img-top\" alt=\"Dr. Brad\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<h5 class=\"fw-bold myP-color\">Dr. Brad</h5>\r\n");
      out.write("						<p class=\"text-secondary\">(Chief Doctor)</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-12 col-sm-6 col-md-4 col-lg-3\">\r\n");
      out.write("				<div class=\"card my-card team-card text-center\">\r\n");
      out.write("					<img src=\"img/doc03.png\" class=\"card-img-top\" alt=\"Dr. Jennifer\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<h5 class=\"fw-bold myP-color\">Dr. Jennifer</h5>\r\n");
      out.write("						<p class=\"text-secondary\">(Chief Surgeon)</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-12 col-sm-6 col-md-4 col-lg-3\">\r\n");
      out.write("				<div class=\"card my-card team-card text-center\">\r\n");
      out.write("					<img src=\"img/doc4.png\" class=\"card-img-top\" alt=\"Dr. Maria\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<h5 class=\"fw-bold myP-color\">Dr. Maria</h5>\r\n");
      out.write("						<p class=\"text-secondary\">(Dean)</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ===== End Our Team ===== -->\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"bg-white text-center mt-5 border-top\">\r\n");
      out.write("  <!-- Grid container -->\r\n");
      out.write("  <div class=\"container p-4 pb-0\">\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("    <section class=\"mb-4\">\r\n");
      out.write("      <!-- Facebook -->\r\n");
      out.write("      <a class=\"btn btn-outline-primary btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-facebook-f\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("      <!-- Twitter -->\r\n");
      out.write("      <a class=\"btn btn-outline-primary btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-twitter\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("      <!-- Google -->\r\n");
      out.write("      <a class=\"btn btn-outline-primary btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-google\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("      <!-- Instagram -->\r\n");
      out.write("      <a class=\"btn btn-outline-primary btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-instagram\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("      <!-- Linkedin -->\r\n");
      out.write("      <a class=\"btn btn-outline-primary btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-linkedin-in\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("      <!-- Github -->\r\n");
      out.write("      <a class=\"btn btn-outline-primary btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-github\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("  <div class=\"text-center p-3\" style=\"background-color: rgba(0, 0, 0, 0.05); color: #6c757d;\">\r\n");
      out.write("    © 2025 Copyright:\r\n");
      out.write("    <a class=\"text-secondary text-decoration-none fw-bold\" href=\"index.jsp\">Doctor Patient Portal</a>\r\n");
      out.write("    (Developer)\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /component/navbar.jsp(129,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userObj and empty doctorObj and empty adminObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\"><i class=\"fa fa-home me-1\"></i> Home</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_appointment.jsp\"><i class=\"fa fa-book me-1\"></i> Appointment</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_login.jsp\"><i class=\"fas fa-sign-in-alt me-1\"></i> User</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"doctor_login.jsp\"><i class=\"fa-solid fa-user-doctor me-1\"></i> Doctor</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"admin_login.jsp\"><i class=\"fa-solid fa-user-shield me-1\"></i> Admin</a></li>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /component/navbar.jsp(138,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_appointment.jsp\"><i class=\"fa fa-book me-1\"></i> Appointment</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"view_appointment.jsp\"><i class=\"fa fa-calendar-check-o me-1\"></i> View</a></li>\r\n");
        out.write("          <li class=\"nav-item dropdown\">\r\n");
        out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
        out.write("              <i class=\"fa-solid fa-circle-user me-1\"></i> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userObj.fullName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("            </a>\r\n");
        out.write("            <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">\r\n");
        out.write("              <li><a class=\"dropdown-item\" href=\"change_password.jsp\">Change Password</a></li>\r\n");
        out.write("              <li><hr class=\"dropdown-divider\"></li>\r\n");
        out.write("              <li><a class=\"dropdown-item\" href=\"userLogout\">Logout</a></li>\r\n");
        out.write("            </ul>\r\n");
        out.write("          </li>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /component/navbar.jsp(154,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty doctorObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          ");
        if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /component/navbar.jsp(155,10) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f0.setUrl("doctor/index.jsp");
    int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
    if (_jspx_th_c_005fredirect_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /component/navbar.jsp(157,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty adminObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          ");
        if (_jspx_meth_c_005fredirect_005f1(_jspx_th_c_005fif_005f3, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f1 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
    // /component/navbar.jsp(158,10) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f1.setUrl("admin/index.jsp");
    int _jspx_eval_c_005fredirect_005f1 = _jspx_th_c_005fredirect_005f1.doStartTag();
    if (_jspx_th_c_005fredirect_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f1);
    return false;
  }
}
