/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.43
 * Generated at: 2025-11-14 13:26:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.hms.entity.Doctor;
import com.hms.dao.DoctorDAO;
import com.hms.entity.User;
import com.hms.entity.Appointment;
import java.util.List;
import com.hms.db.DBConnection;
import com.hms.dao.AppointmentDAO;

public final class view_005fappointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/component/allcss.jsp", Long.valueOf(1763046081998L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1754389174666L));
    _jspx_dependants.put("/component/navbar.jsp", Long.valueOf(1763043036559L));
    _jspx_dependants.put("jar:file:/Z:/project_workspace_new/Doctor-Patient-Portal-AdvanceJavaWebProject-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Doctor-Patient-Portal/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hms.db.DBConnection");
    _jspx_imports_classes.add("com.hms.entity.Doctor");
    _jspx_imports_classes.add("com.hms.entity.User");
    _jspx_imports_classes.add("com.hms.dao.DoctorDAO");
    _jspx_imports_classes.add("com.hms.entity.Appointment");
    _jspx_imports_classes.add("com.hms.dao.AppointmentDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>My Appointments</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("    href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("    crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome CSS (for icons) -->\r\n");
      out.write("<link\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\"\r\n");
      out.write("    integrity=\"sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==\"\r\n");
      out.write("    crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script\r\n");
      out.write("    src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Global Custom Styles -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       THEME COLORS & VARIABLES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    :root {\r\n");
      out.write("        --primary-color: #4568dc;\r\n");
      out.write("        --primary-hover: #3654b3;\r\n");
      out.write("        --accent-color: #00c6ff;\r\n");
      out.write("        --light-bg: #f8f9fa;\r\n");
      out.write("        --dark-text: #2d2d2d;\r\n");
      out.write("        --card-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        --transition-speed: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif;\r\n");
      out.write("        background-color: var(--light-bg);\r\n");
      out.write("        color: var(--dark-text);\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        REUSABLE CLASSES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-bg-color { background-color: var(--primary-color) !important; }\r\n");
      out.write("    .myP-color { color: var(--primary-color) !important; }\r\n");
      out.write("    .my-hover:hover { color: var(--primary-hover) !important; }\r\n");
      out.write("\r\n");
      out.write("    /* Button Enhancements */\r\n");
      out.write("    .btn.my-bg-color {\r\n");
      out.write("        background-color: var(--primary-color);\r\n");
      out.write("        border-color: var(--primary-color);\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: background-color var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("    .btn.my-bg-color:hover {\r\n");
      out.write("        background-color: var(--primary-hover);\r\n");
      out.write("        border-color: var(--primary-hover);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       NAVBAR STYLING\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .navbar {\r\n");
      out.write("        box-shadow: 0 2px 6px rgba(0,0,0,0.1);\r\n");
      out.write("        background: linear-gradient(90deg, var(--primary-color), var(--accent-color));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .navbar-brand {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #fff !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .nav-link, .navbar .dropdown-toggle {\r\n");
      out.write("        color: #fff !important;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: color var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .nav-link:hover {\r\n");
      out.write("        color: #e2e2e2 !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-menu {\r\n");
      out.write("        border: none;\r\n");
      out.write("        box-shadow: var(--card-shadow);\r\n");
      out.write("        border-radius: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        FORMS & INPUTS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .form-control, .form-select {\r\n");
      out.write("        border-radius: 0.5rem;\r\n");
      out.write("        transition: all var(--transition-speed);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control:focus, .form-select:focus {\r\n");
      out.write("        border-color: var(--primary-color);\r\n");
      out.write("        box-shadow: 0 0 0 0.25rem rgba(69,104,220,0.25);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        CARDS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-card {\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 0.75rem;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        box-shadow: var(--card-shadow);\r\n");
      out.write("        transition: transform 0.2s ease, box-shadow 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .my-card:hover {\r\n");
      out.write("        transform: translateY(-3px);\r\n");
      out.write("        box-shadow: 0 8px 18px rgba(0, 0, 0, 0.12);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        TABLE STYLING\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .table thead {\r\n");
      out.write("        background-color: var(--primary-color);\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table th {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        BACKGROUND UTILITIES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .my-bg-img {\r\n");
      out.write("        background: linear-gradient(rgba(0, 0, 0, .4), rgba(0, 0, 0, .4)),\r\n");
      out.write("                    url(\"img/hospital1.jpg\") center/cover no-repeat;\r\n");
      out.write("        height: 25vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-shadow: 0 2px 4px rgba(0,0,0,0.6);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       LOGIN & SIGNUP PAGES\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .login-container {\r\n");
      out.write("        min-height: 90vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        padding: 2rem 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-card {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 450px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("       RESPONSIVENESS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .navbar .nav-link { font-size: 0.95rem; }\r\n");
      out.write("        .my-bg-img { height: 20vh; background-position: top center; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("        .login-card { padding: 1rem; }\r\n");
      out.write("        .my-bg-img { height: 18vh; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ======================================\r\n");
      out.write("        ANIMATION HELPERS\r\n");
      out.write("       ====================================== */\r\n");
      out.write("    .fade-in {\r\n");
      out.write("        animation: fadeIn 0.8s ease-in-out forwards;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeIn {\r\n");
      out.write("        from { opacity: 0; transform: translateY(10px); }\r\n");
      out.write("        to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    /* ------------------------------\r\n");
      out.write("       GLASS MORPHISM THEME\r\n");
      out.write("    ------------------------------ */\r\n");
      out.write("    \r\n");
      out.write("    body {\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("        background-color: #f0f8ff; \r\n");
      out.write("        font-family: 'Poppins', sans-serif;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* --- BLURRED BACKGROUND IMAGE (Behind Content) --- */\r\n");
      out.write("    body::before {\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        background-image: url('img/hospital1.jpg');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("        background-attachment: fixed;\r\n");
      out.write("        filter: blur(3px) brightness(1.1); \r\n");
      out.write("        opacity: 0.6; \r\n");
      out.write("        z-index: -1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Navbar remains sharp on top */\r\n");
      out.write("    .navbar {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        z-index: 1000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Page Banner (Slightly frosted glass header) */\r\n");
      out.write("    .page-banner {\r\n");
      out.write("        margin-top: 80px;\r\n");
      out.write("        padding: 50px 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        /* Frosted Glass Effect */\r\n");
      out.write("        background: rgba(255, 255, 255, 0.7);\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("        border-bottom: 1px solid rgba(255, 255, 255, 0.5);\r\n");
      out.write("        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        z-index: 10;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-banner h2 {\r\n");
      out.write("        color: #2196F3; \r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        font-size: 2.2rem;\r\n");
      out.write("        text-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Appointment Container for Centering */\r\n");
      out.write("    .appointment-container {\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        padding: 40px 20px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: flex-start;\r\n");
      out.write("        z-index: 10; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Main Content Card (Strong Glass Effect) */\r\n");
      out.write("    .appointment-card {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 1100px;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.95); /* Slightly less transparent */\r\n");
      out.write("        backdrop-filter: blur(15px);\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        box-shadow: 0 10px 40px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        border: 1px solid rgba(255, 255, 255, 0.5);\r\n");
      out.write("        padding: 35px;\r\n");
      out.write("        color: #000;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .appointment-card h3 {\r\n");
      out.write("        color: #2196F3; \r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        margin-bottom: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ------------------------------\r\n");
      out.write("       TABLE STYLING (Desktop/Tablet)\r\n");
      out.write("    ------------------------------ */\r\n");
      out.write("    .table-custom th {\r\n");
      out.write("        background: #2196F3; \r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table-custom tbody tr {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.98); \r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        display: table-row;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* Remove default table spacing and add custom spacing via margin-bottom */\r\n");
      out.write("    .table-custom {\r\n");
      out.write("        border-collapse: separate;\r\n");
      out.write("        border-spacing: 0 10px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .table-custom td {\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .badge {\r\n");
      out.write("        font-size: 0.85rem;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 6px 14px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        min-width: 80px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* ------------------------------\r\n");
      out.write("       MOBILE CARD STYLING \r\n");
      out.write("    ------------------------------ */\r\n");
      out.write("    /* Hide cards by default, show table */\r\n");
      out.write("    .mobile-cards {\r\n");
      out.write("        display: none; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        /* Hide table on mobile */\r\n");
      out.write("        .table-responsive {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        /* Show cards on mobile */\r\n");
      out.write("        .mobile-cards {\r\n");
      out.write("            display: block !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .appointment-card {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .appt-item-card {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border-left: 5px solid #2196F3; /* Blue accent */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-detail {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 8px 0;\r\n");
      out.write("            border-bottom: 1px dashed #eee;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Highlight Name and Doctor at the top */\r\n");
      out.write("        .card-detail:nth-child(1) {\r\n");
      out.write("            border-bottom: 2px solid #2196F3;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("            font-size: 1.1em;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #2196F3;\r\n");
      out.write("            flex-direction: column; \r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-detail:nth-child(1) .card-value {\r\n");
      out.write("        	font-size: 0.8em;\r\n");
      out.write("        	font-weight: 500;\r\n");
      out.write("        	color: #6c757d;\r\n");
      out.write("        	margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-detail:last-child {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            flex-basis: 40%;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-value {\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            flex-basis: 60%;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            word-break: break-all;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* ====== KILLER BLUE THEME NAVBAR ====== */\r\n");
      out.write(".blue-navbar {\r\n");
      out.write("  background: linear-gradient(90deg, #007bff 0%, #0056b3 100%);\r\n");
      out.write("  box-shadow: 0 4px 18px rgba(0, 91, 255, 0.35);\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  padding: 0.6rem 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blue-navbar.scrolled {\r\n");
      out.write("  background: linear-gradient(90deg, #0056b3 0%, #003d99 100%);\r\n");
      out.write("  box-shadow: 0 6px 25px rgba(0, 0, 0, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Brand Styling */\r\n");
      out.write(".blue-navbar .navbar-brand {\r\n");
      out.write("  font-weight: 800;\r\n");
      out.write("  font-size: 1.3rem;\r\n");
      out.write("  color: #ffffff !important;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  gap: 8px;\r\n");
      out.write("  text-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nav Links */\r\n");
      out.write(".blue-navbar .nav-link {\r\n");
      out.write("  color: #ffffff !important;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  letter-spacing: 0.5px;\r\n");
      out.write("  padding: 0.6rem 1.2rem;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("  margin: 0 2px;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blue-navbar .nav-link:hover {\r\n");
      out.write("  background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("  box-shadow: 0 0 10px rgba(255, 255, 255, 0.3);\r\n");
      out.write("  transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Animated underline effect */\r\n");
      out.write(".blue-navbar .nav-link::after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 6px;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write(".blue-navbar .nav-link:hover::after {\r\n");
      out.write("  width: 60%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dropdown */\r\n");
      out.write(".blue-navbar .dropdown-menu {\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2);\r\n");
      out.write("  animation: fadeIn 0.25s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".blue-navbar .dropdown-item {\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  color: #333;\r\n");
      out.write("  border-radius: 6px;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".blue-navbar .dropdown-item:hover {\r\n");
      out.write("  background: linear-gradient(90deg, #007bff, #0056b3);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  transform: translateX(4px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Toggler */\r\n");
      out.write(".navbar-toggler {\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("  border-radius: 6px;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".navbar-toggler:hover {\r\n");
      out.write("  background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Animation */\r\n");
      out.write("@keyframes fadeIn {\r\n");
      out.write("  from { opacity: 0; transform: translateY(-10px); }\r\n");
      out.write("  to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media (max-width: 992px) {\r\n");
      out.write("  .blue-navbar .nav-link {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin: 6px 0;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark sticky-top blue-navbar\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("      <i class=\"fa-solid fa-hospital\"></i> Doctor Patient Portal\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("      data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("      aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("      aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Guest -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- User -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Doctor/Admin Redirect -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener(\"scroll\", () => {\r\n");
      out.write("  const nav = document.querySelector(\".blue-navbar\");\r\n");
      out.write("  if (window.scrollY > 10) nav.classList.add(\"scrolled\");\r\n");
      out.write("  else nav.classList.remove(\"scrolled\");\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Redirect if not logged in -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Header -->\r\n");
      out.write("    <div class=\"page-banner\">\r\n");
      out.write("        <h2><i class=\"fa fa-calendar-check me-2\"></i> My Appointments</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Appointment List -->\r\n");
      out.write("    <div class=\"appointment-container\">\r\n");
      out.write("        <div class=\"appointment-card\">\r\n");
      out.write("            <h3><i class=\"fa fa-list-ul me-2\"></i> Appointment List</h3>\r\n");
      out.write("\r\n");
      out.write("            ");

                User user = (User) session.getAttribute("userObj");
                DoctorDAO dDAO = new DoctorDAO(DBConnection.getConn());
                AppointmentDAO appDAO = new AppointmentDAO(DBConnection.getConn());
                List<Appointment> list = appDAO.getAllAppointmentByLoginUser(user.getId());
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if (list.isEmpty()) { 
      out.write("\r\n");
      out.write("                <div class=\"text-center text-muted py-4\">You have no scheduled appointments.</div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                <!-- 1. DESKTOP/TABLET TABLE VIEW -->\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                    <table class=\"table table-custom align-middle\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>Patient Name</th>\r\n");
      out.write("                                <th>Doctor</th>\r\n");
      out.write("                                <th>Date & Time</th>\r\n");
      out.write("                                <th>Gender/Age</th>\r\n");
      out.write("                                <th>Diseases</th>\r\n");
      out.write("                                <th>Phone</th>\r\n");
      out.write("                                <th class=\"text-center\">Status</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");

                                for (Appointment apptList : list) {
                                    Doctor doctor = dDAO.getDoctorById(apptList.getDoctorId());
                            
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>");
      out.print(apptList.getFullName());
      out.write("</td>\r\n");
      out.write("                                <td><i class=\"fa-solid fa-user-md me-1 text-info\"></i> ");
      out.print(doctor.getFullName());
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(apptList.getAppointmentDate());
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(apptList.getGender());
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(apptList.getAge());
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(apptList.getDiseases());
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(apptList.getPhone());
      out.write("</td>\r\n");
      out.write("                                <td class=\"text-center\">\r\n");
      out.write("                                    ");

                                        if ("Pending".equals(apptList.getStatus())) {
                                    
      out.write(" \r\n");
      out.write("                                        <span class=\"badge bg-warning\">Pending</span> \r\n");
      out.write("                                    ");

                                        } else {
                                    
      out.write(" \r\n");
      out.write("                                        <span class=\"badge bg-success\">");
      out.print(apptList.getStatus());
      out.write("</span> \r\n");
      out.write("                                    ");

                                        }
                                    
      out.write("\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            ");

                                }
                            
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 2. MOBILE CARD VIEW -->\r\n");
      out.write("                <div class=\"mobile-cards\">\r\n");
      out.write("                    ");
 for (Appointment apptList : list) {
                        Doctor doctor = dDAO.getDoctorById(apptList.getDoctorId());
                    
      out.write("\r\n");
      out.write("                    <div class=\"appt-item-card\">\r\n");
      out.write("                        <!-- Name and Doctor (Header) -->\r\n");
      out.write("                        <div class=\"card-detail\">\r\n");
      out.write("                            ");
      out.print(apptList.getFullName());
      out.write("\r\n");
      out.write("                            <div class=\"card-value\"><i class=\"fa-solid fa-user-md me-1\"></i> Dr. ");
      out.print( doctor.getFullName());
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- Status -->\r\n");
      out.write("                        <div class=\"card-detail\">\r\n");
      out.write("                            <div class=\"card-label\">Status</div>\r\n");
      out.write("                            <div class=\"card-value\">\r\n");
      out.write("                                ");

                                    if ("Pending".equals(apptList.getStatus())) {
                                
      out.write(" <span class=\"badge bg-warning\">Pending</span> ");

                                    } else {
                                
      out.write(" <span class=\"badge bg-success\">");
      out.print(apptList.getStatus());
      out.write("</span> ");

                                    }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"card-detail\">\r\n");
      out.write("                            <div class=\"card-label\">Appointment Date</div>\r\n");
      out.write("                            <div class=\"card-value\"><i class=\"fa-solid fa-calendar-alt me-1\"></i> ");
      out.print( apptList.getAppointmentDate());
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-detail\">\r\n");
      out.write("                            <div class=\"card-label\">Gender / Age</div>\r\n");
      out.write("                            <div class=\"card-value\">");
      out.print( apptList.getGender() );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print( apptList.getAge() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-detail\">\r\n");
      out.write("                            <div class=\"card-label\">Diseases</div>\r\n");
      out.write("                            <div class=\"card-value\">");
      out.print( apptList.getDiseases());
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-detail\">\r\n");
      out.write("                            <div class=\"card-label\">Phone</div>\r\n");
      out.write("                            <div class=\"card-value\"><i class=\"fa-solid fa-phone me-1\"></i> ");
      out.print( apptList.getPhone());
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /component/navbar.jsp(129,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userObj and empty doctorObj and empty adminObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\"><i class=\"fa fa-home me-1\"></i> Home</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_appointment.jsp\"><i class=\"fa fa-book me-1\"></i> Appointment</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_login.jsp\"><i class=\"fas fa-sign-in-alt me-1\"></i> User</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"doctor_login.jsp\"><i class=\"fa-solid fa-user-doctor me-1\"></i> Doctor</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"admin_login.jsp\"><i class=\"fa-solid fa-user-shield me-1\"></i> Admin</a></li>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /component/navbar.jsp(138,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_appointment.jsp\"><i class=\"fa fa-book me-1\"></i> Appointment</a></li>\r\n");
        out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"view_appointment.jsp\"><i class=\"fa fa-calendar-check-o me-1\"></i> View</a></li>\r\n");
        out.write("          <li class=\"nav-item dropdown\">\r\n");
        out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
        out.write("              <i class=\"fa-solid fa-circle-user me-1\"></i> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userObj.fullName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("            </a>\r\n");
        out.write("            <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">\r\n");
        out.write("              <li><a class=\"dropdown-item\" href=\"change_password.jsp\">Change Password</a></li>\r\n");
        out.write("              <li><hr class=\"dropdown-divider\"></li>\r\n");
        out.write("              <li><a class=\"dropdown-item\" href=\"userLogout\">Logout</a></li>\r\n");
        out.write("            </ul>\r\n");
        out.write("          </li>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /component/navbar.jsp(154,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty doctorObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          ");
        if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /component/navbar.jsp(155,10) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f0.setUrl("doctor/index.jsp");
    int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
    if (_jspx_th_c_005fredirect_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /component/navbar.jsp(157,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty adminObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          ");
        if (_jspx_meth_c_005fredirect_005f1(_jspx_th_c_005fif_005f3, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f1 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
    // /component/navbar.jsp(158,10) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f1.setUrl("admin/index.jsp");
    int _jspx_eval_c_005fredirect_005f1 = _jspx_th_c_005fredirect_005f1.doStartTag();
    if (_jspx_th_c_005fredirect_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent(null);
    // /view_appointment.jsp(239,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userObj }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        ");
        if (_jspx_meth_c_005fredirect_005f2(_jspx_th_c_005fif_005f4, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f2 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
    // /view_appointment.jsp(240,8) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f2.setUrl("/user_login.jsp");
    int _jspx_eval_c_005fredirect_005f2 = _jspx_th_c_005fredirect_005f2.doStartTag();
    if (_jspx_th_c_005fredirect_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f2);
    return false;
  }
}
